apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-example
            image: alpine
            args:
            - /bin/sh
            - -c
            - echo `hostname` ":" `date` > /web.html
            volumeMounts:
            - name: cron
              mountPath: /web.html
          volumes:
          - name: cron
            persistentVolumeClaim:
              claimName: web
          restartPolicy: OnFailure
