apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: httpd
        image: httpd:2.4
        volumeMounts:
        - mountPath: "/usr/local/apache2/htdocs/index.html"
          name: fileweb
        ports:
        - containerPort: 80
      volumes:
        - name: fileweb
          persistentVolumeClaim:
            claimName: web
